function transformMatrix = transformationMatrixLAB(theta)
% Matrix multiplication with RGB 0:1 gives YCbCr 0:1 -0.5:0.5 -0.5:0.5
transformMatrix = [1./3.,1./3.,1./3.;
    -1.*(sec(theta - (pi*floor(0.5 + (3*theta)/pi))/3.)*(cos(theta) + sqrt(3)*sin(theta)))/4., ...
    cos(theta)*sec(theta - (pi*floor(0.5 + (3*theta)/pi))/3.)/2. , ...
    (sec(theta - (pi*floor(0.5 + (3*theta)/pi))/3.)*(-cos(theta) + sqrt(3)*sin(theta)))/4. ; ...
    (sec((pi - 6*mod(theta, pi/3.))/6.)*(-(sqrt(3)*cos(theta)) + sin(theta)))/4., ...
    -(sec((pi - 6*mod(theta, pi/3.))/6.)*sin(theta))/2., ...
    (sec((pi - 6*mod(theta, pi/3.))/6.)*(sqrt(3)*cos(theta) + sin(theta)))/4. ];
end